name: Development
on:
  push:
    branches:
      - dev
jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 18
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build:storybook

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs-build
          CLEAN: true
